/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;


import ec.edu.ups.Direcciones.BuscarDireccion;
import ec.edu.ups.Direcciones.ActualizarDirecciones;
import ec.edu.ups.Direcciones.ListarDirecciones;
import ec.edu.ups.Direcciones.EliminarDireccion;
import java.awt.Dimension;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.RandomAccessFile;


/**
 *
 * @author ASUS
 */
public class VistaPrincipal extends javax.swing.JFrame {

    private VentanaCrear crear;
    private VentanaBuscar leer;
    private VentanaEliminar eliminar;
    private VentanaActualizar actualizar;
    private VentanaLista listarPersonas;
   // private CrearDireccion crearDireccion;
    private BuscarDireccion  buscarDirecion;
    private ActualizarDirecciones actualizarDirecciones;
    private EliminarDireccion eliminarDireccion;
    private ListarDirecciones listarDirecciones;
    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
        this.setSize(1200, 800);
        this.setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        itmCrear = new javax.swing.JMenuItem();
        itmLeer = new javax.swing.JMenuItem();
        itmActualizar = new javax.swing.JMenuItem();
        itmEliminar = new javax.swing.JMenuItem();
        itmListar = new javax.swing.JMenuItem();
        fileMenu1 = new javax.swing.JMenu();
        itmCrear1 = new javax.swing.JMenuItem();
        itmLeer1 = new javax.swing.JMenuItem();
        itmActualizar1 = new javax.swing.JMenuItem();
        itmEliminar1 = new javax.swing.JMenuItem();
        itmListar1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        fileMenu.setMnemonic('f');
        fileMenu.setText("Persona");

        itmCrear.setMnemonic('o');
        itmCrear.setText("Crear");
        itmCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCrearActionPerformed(evt);
            }
        });
        fileMenu.add(itmCrear);

        itmLeer.setMnemonic('s');
        itmLeer.setText("Leer");
        itmLeer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmLeerActionPerformed(evt);
            }
        });
        fileMenu.add(itmLeer);

        itmActualizar.setMnemonic('a');
        itmActualizar.setText("Actualizar");
        itmActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmActualizarActionPerformed(evt);
            }
        });
        fileMenu.add(itmActualizar);

        itmEliminar.setMnemonic('x');
        itmEliminar.setText("Eliminar");
        itmEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmEliminarActionPerformed(evt);
            }
        });
        fileMenu.add(itmEliminar);

        itmListar.setText("Listar");
        itmListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmListarActionPerformed(evt);
            }
        });
        fileMenu.add(itmListar);

        menuBar.add(fileMenu);

        fileMenu1.setMnemonic('f');
        fileMenu1.setText("Direciones");

        itmCrear1.setMnemonic('o');
        itmCrear1.setText("Crear");
        itmCrear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCrear1ActionPerformed(evt);
            }
        });
        fileMenu1.add(itmCrear1);

        itmLeer1.setMnemonic('s');
        itmLeer1.setText("Leer");
        itmLeer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmLeer1ActionPerformed(evt);
            }
        });
        fileMenu1.add(itmLeer1);

        itmActualizar1.setMnemonic('a');
        itmActualizar1.setText("Actualizar");
        itmActualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmActualizar1ActionPerformed(evt);
            }
        });
        fileMenu1.add(itmActualizar1);

        itmEliminar1.setMnemonic('x');
        itmEliminar1.setText("Eliminar");
        itmEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmEliminar1ActionPerformed(evt);
            }
        });
        fileMenu1.add(itmEliminar1);

        itmListar1.setText("Listar");
        itmListar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmListar1ActionPerformed(evt);
            }
        });
        fileMenu1.add(itmListar1);

        menuBar.add(fileMenu1);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itmEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmEliminarActionPerformed

        if (eliminar == null || eliminar.isVisible() == false) {
            eliminar = new VentanaEliminar();
            eliminar.setVisible(true);
            Dimension dimensionEscritorio = desktopPane.getSize();
            Dimension dimension = eliminar.getSize();
            eliminar.setLocation((dimensionEscritorio.width - dimension.width) / 2, (dimensionEscritorio.height - dimension.height) / 2);
            desktopPane.add(eliminar);
        }
    }//GEN-LAST:event_itmEliminarActionPerformed

    private void itmCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCrearActionPerformed
        // TODO add your handling code here:
        if (crear == null || crear.isVisible() == false) {
            crear = new VentanaCrear();
            crear.setVisible(true);
            Dimension dimensionEscritorio = desktopPane.getSize();
            Dimension dimension = crear.getSize();
            crear.setLocation((dimensionEscritorio.width - dimension.width) / 2, (dimensionEscritorio.height - dimension.height) / 2);
            desktopPane.add(crear);
        }
    }//GEN-LAST:event_itmCrearActionPerformed

    private void itmLeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmLeerActionPerformed

        if (leer == null || leer.isVisible() == false) {
            
           leer= new VentanaBuscar();
            leer.setVisible(true);
            Dimension dimensionEscritorio = desktopPane.getSize();
            Dimension dimension = leer.getSize();
            leer.setLocation((dimensionEscritorio.width - dimension.width) / 2, (dimensionEscritorio.height - dimension.height) / 2);
            desktopPane.add(leer);
        }
    }//GEN-LAST:event_itmLeerActionPerformed

    private void itmActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmActualizarActionPerformed
        // TODO add your handling code here:
        if (actualizar == null || actualizar.isVisible() == false) {
            actualizar = new VentanaActualizar();
            actualizar.setVisible(true);
            Dimension dimensionEscritorio = desktopPane.getSize();
            Dimension dimension = actualizar.getSize();
            actualizar.setLocation((dimensionEscritorio.width - dimension.width) / 2, (dimensionEscritorio.height - dimension.height) / 2);
            desktopPane.add(actualizar);
        }
    }//GEN-LAST:event_itmActualizarActionPerformed

    private void itmListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmListarActionPerformed
        // TODO add your handling code here:
        if (listarPersonas == null || listarPersonas.isVisible() == false) {
            listarPersonas = new VentanaLista();
            listarPersonas.setVisible(true);
            Dimension dimensionEscritorio = desktopPane.getSize();
            Dimension dimension = listarPersonas.getSize();
            listarPersonas.setLocation((dimensionEscritorio.width - dimension.width) / 2, (dimensionEscritorio.height - dimension.height) / 2);
            desktopPane.add(listarPersonas);
        }
    }//GEN-LAST:event_itmListarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowClosing

    private void itmCrear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCrear1ActionPerformed
        // TODO add your handling code here:
     /* if (crearDireccion == null || crearDireccion.isVisible() == false) {
           // crearDireccion = new CrearDireccion();
            crearDireccion.setVisible(true);
            Dimension dimensionEscritorio = desktopPane.getSize();
            Dimension dimension = crearDireccion.getSize();
            crearDireccion.setLocation((dimensionEscritorio.width - dimension.width) / 2, (dimensionEscritorio.height - dimension.height) / 2);
            desktopPane.add(crearDireccion);
        }
        */
    }//GEN-LAST:event_itmCrear1ActionPerformed

    private void itmLeer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmLeer1ActionPerformed
        // TODO add your handling code here:
         if (buscarDirecion == null || buscarDirecion.isVisible() == false) {
            
           buscarDirecion= new BuscarDireccion();
            buscarDirecion.setVisible(true);
            Dimension dimensionEscritorio = desktopPane.getSize();
            Dimension dimension = buscarDirecion.getSize();
            buscarDirecion.setLocation((dimensionEscritorio.width - dimension.width) / 2, (dimensionEscritorio.height - dimension.height) / 2);
            desktopPane.add(buscarDirecion);
        }
    }//GEN-LAST:event_itmLeer1ActionPerformed

    private void itmActualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmActualizar1ActionPerformed
        // TODO add your handling code here:
         if (actualizarDirecciones == null || actualizarDirecciones.isVisible() == false) {
            actualizarDirecciones = new ActualizarDirecciones();
            actualizarDirecciones.setVisible(true);
            Dimension dimensionEscritorio = desktopPane.getSize();
            Dimension dimension = actualizarDirecciones.getSize();
            actualizarDirecciones.setLocation((dimensionEscritorio.width - dimension.width) / 2, (dimensionEscritorio.height - dimension.height) / 2);
            desktopPane.add(actualizarDirecciones);
        }
    }//GEN-LAST:event_itmActualizar1ActionPerformed

    private void itmEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmEliminar1ActionPerformed
        // TODO add your handling code here:
         if (eliminarDireccion == null || eliminarDireccion.isVisible() == false) {
            eliminarDireccion = new EliminarDireccion();
            eliminarDireccion.setVisible(true);
            Dimension dimensionEscritorio = desktopPane.getSize();
            Dimension dimension = eliminarDireccion.getSize();
            eliminarDireccion.setLocation((dimensionEscritorio.width - dimension.width) / 2, (dimensionEscritorio.height - dimension.height) / 2);
            desktopPane.add(eliminarDireccion);
        }
    }//GEN-LAST:event_itmEliminar1ActionPerformed

    private void itmListar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmListar1ActionPerformed
        // TODO add your handling code here:
         if (listarDirecciones == null || listarDirecciones.isVisible() == false) {
            listarDirecciones = new ListarDirecciones();
            listarDirecciones.setVisible(true);
            Dimension dimensionEscritorio = desktopPane.getSize();
            Dimension dimension = listarDirecciones.getSize();
            listarDirecciones.setLocation((dimensionEscritorio.width - dimension.width) / 2, (dimensionEscritorio.height - dimension.height) / 2);
            desktopPane.add(listarDirecciones);
        }
    }//GEN-LAST:event_itmListar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu fileMenu1;
    private javax.swing.JMenuItem itmActualizar;
    private javax.swing.JMenuItem itmActualizar1;
    private javax.swing.JMenuItem itmCrear;
    private javax.swing.JMenuItem itmCrear1;
    private javax.swing.JMenuItem itmEliminar;
    private javax.swing.JMenuItem itmEliminar1;
    private javax.swing.JMenuItem itmLeer;
    private javax.swing.JMenuItem itmLeer1;
    private javax.swing.JMenuItem itmListar;
    private javax.swing.JMenuItem itmListar1;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
